# Generated by Django 4.2.14 on 2024-07-17 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toowitter_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='view',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
