# Generated by Django 4.2.14 on 2024-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toowitter_api', '0002_tweet_date_alter_like_id_alter_tweet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
