# Generated by Django 4.2.14 on 2024-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toowitter_api', '0004_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
